#define MAZEWIDTH 20
#define MAZEHEIGHT 20
#define CHROLENGTH 200
#define POPULATION 400
#define GENLENGTH  2
#define CROSSOVER_RATE 0.7
#define MUTATION_RATE 0.001
#define XSTART 19
#define YSTART 18
#define XEND   0
#define YEND   2